# Generated by Django 3.0.1 on 2020-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=191)),
                ('subject_code', models.CharField(max_length=191)),
                ('subject_start', models.CharField(max_length=191)),
                ('subject_duration', models.CharField(max_length=191)),
                ('subject_hod', models.CharField(max_length=191)),
                ('subject_students_number', models.CharField(max_length=191)),
                ('subject_photo', models.ImageField(upload_to='subjects')),
                ('subject_details', models.TextField()),
            ],
        ),
    ]
