# Generated by Django 3.0.1 on 2020-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
