# Generated by Django 3.0.1 on 2020-01-05 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Subject', '0002_subject_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_class',
            field=models.CharField(default=django.utils.timezone.now, max_length=191),
            preserve_default=False,
        ),
    ]
