# Generated by Django 3.0.1 on 2020-01-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Subject', '0003_subject_subject_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_Subject.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_Subject.Subject')),
            ],
        ),
    ]
