# Generated by Django 3.0.1 on 2020-01-04 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=191, null=True)),
                ('last_name', models.CharField(blank=True, max_length=191, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=191, null=True)),
                ('profile_photo', models.ImageField(upload_to='teacher_profile')),
                ('joined_date', models.CharField(blank=True, max_length=191, null=True)),
                ('department', models.CharField(blank=True, max_length=191, null=True)),
                ('designation', models.CharField(blank=True, max_length=191, null=True)),
                ('gender', models.CharField(blank=True, max_length=191, null=True)),
                ('dob', models.CharField(blank=True, max_length=191, null=True)),
                ('address', models.CharField(blank=True, max_length=191, null=True)),
                ('education', models.CharField(blank=True, max_length=191, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
