# Generated by Django 3.0.1 on 2020-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0002_teacherprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='education',
            field=models.TextField(),
        ),
    ]
