# Generated by Django 3.0.1 on 2020-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=191)),
                ('last_name', models.CharField(max_length=191)),
                ('admission_number', models.CharField(max_length=191)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reg_date', models.CharField(max_length=191)),
                ('form_class', models.CharField(max_length=191)),
                ('gender', models.CharField(max_length=191)),
                ('mobile_number', models.CharField(blank=True, max_length=191, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=191, null=True)),
                ('parent_mobile_number', models.CharField(blank=True, max_length=191, null=True)),
                ('dob', models.CharField(max_length=191)),
                ('address', models.TextField()),
                ('student_photo', models.ImageField(upload_to='student_picture')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
