# Generated by Django 3.0.1 on 2020-01-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Oauth', '0002_teacherprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=191)),
                ('starting_year', models.CharField(max_length=191)),
                ('student_capacity', models.CharField(max_length=191)),
                ('department_details', models.TextField(max_length=191)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oauth.TeacherProfile')),
            ],
        ),
    ]
